version: "3.4"

services:
  api:
    build: ./bee_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment: 
      - ACTA_RECIBIDO_CRUD=${ACTA_RECIBIDO_CRUD}
      - ENTRADAS_CRUD=${ENTRADAS_CRUD}
      - PARAMETROS_GOBIERNO_CRUD=${PARAMETROS_GOBIERNO_CRUD}
      - OIKOS_CRUD=${OIKOS_CRUD}
      - ADMINISTRATIVA_JBPM=${ADMINISTRATIVA_JBPM}
      - ADMINISTRATIVA_SERVICE=${ADMINISTRATIVA_SERVICE}
      - ARKA_MID_HTTP_PORT=${PORT}
      - RUN_MODE=dev
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:${SERVICE_NAME}.localhost
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -v -u ./...; bee run -downdoc=true -gendoc=true'
    networks:
      - back_end

volumes:
  gosrc:
networks:
  back_end:
    external: true
